//
//  LocalWineCatalog.swift
//  Vitis
//
//  Yerel şarap listesi. Ağ olmadan anında arama; ~1 sn içinde sonuç.
//

import Foundation

enum LocalWineCatalog {
    private static let entries: [(name: String, brand: String)] = [
        ("Shiraz", "Casillero del Diablo"),
        ("Cabernet Sauvignon", "Casillero del Diablo"),
        ("Chardonnay", "Casillero del Diablo"),
        ("Merlot", "Casillero del Diablo"),
        ("Shiraz", "Yellow Tail"),
        ("Chardonnay", "Yellow Tail"),
        ("Cabernet Sauvignon", "Yellow Tail"),
        ("Merlot", "Yellow Tail"),
        ("Pinot Grigio", "Yellow Tail"),
        ("Chardonnay", "Jacob's Creek"),
        ("Shiraz", "Jacob's Creek"),
        ("Cabernet Sauvignon", "Jacob's Creek"),
        ("Merlot", "Jacob's Creek"),
        ("Chardonnay", "Kendall-Jackson"),
        ("Cabernet Sauvignon", "Kendall-Jackson"),
        ("Chardonnay", "Barefoot"),
        ("Merlot", "Barefoot"),
        ("Pinot Grigio", "Barefoot"),
        ("Moscato", "Barefoot"),
        ("Chardonnay", "Josh Cellars"),
        ("Cabernet Sauvignon", "Josh Cellars"),
        ("Merlot", "Josh Cellars"),
        ("Cabernet Sauvignon", "Robert Mondavi"),
        ("Chardonnay", "Robert Mondavi"),
        ("Reserva Tempranillo", "Campo Viejo"),
        ("Rioja", "Campo Viejo"),
        ("Garnacha", "Campo Viejo"),
        ("Prosecco", "La Marca"),
        ("Pinot Noir", "La Crema"),
        ("Chardonnay", "La Crema"),
        ("Cabernet Sauvignon", "Woodbridge"),
        ("Chardonnay", "Woodbridge"),
        ("Merlot", "Woodbridge"),
        ("Malbec", "Alamos"),
        ("Malbec", "Catena Zapata"),
        ("Cabernet Sauvignon", "Catena Zapata"),
        ("Chianti", "Ruffino"),
        ("Pinot Grigio", "Ruffino"),
        ("Prosecco", "Ruffino"),
        ("Côtes du Rhône", "E. Guigal"),
        ("Châteauneuf-du-Pape", "E. Guigal"),
        ("Rioja Reserva", "Marqués de Riscal"),
        ("Chardonnay", "Lindeman's"),
        ("Bin 65 Chardonnay", "Lindeman's"),
        ("Shiraz", "Lindeman's"),
        ("Sauvignon Blanc", "Oyster Bay"),
        ("Pinot Noir", "Oyster Bay"),
        ("Chardonnay", "Oyster Bay"),
        ("Noble One", "De Bortoli"),
        ("Shiraz", "Penfolds"),
        ("Grange", "Penfolds"),
        ("Bin 389", "Penfolds"),
        ("Riesling", "Dr. Loosen"),
        ("Cabernet Sauvignon", "Beringer"),
        ("Chardonnay", "Beringer"),
        ("White Zinfandel", "Beringer"),
        ("Merlot", "Columbia Crest"),
        ("Cabernet Sauvignon", "Columbia Crest"),
        ("Chardonnay", "Columbia Crest"),
        ("Cabernet Sauvignon", "Cavit"),
        ("Pinot Grigio", "Cavit"),
        ("Chardonnay", "Santa Margherita"),
        ("Pinot Grigio", "Santa Margherita"),
        ("Prosecco", "Santa Margherita"),
        ("Chardonnay", "Butter"),
        ("Cabernet Sauvignon", "Cupcake"),
        ("Chardonnay", "Cupcake"),
        ("Prosecco", "Cupcake"),
        ("Red Blend", "Apothic"),
        ("Cabernet Sauvignon", "Apothic"),
        ("Chardonnay", "Bread and Butter"),
        ("Pinot Noir", "Bread and Butter"),
        ("Sauvignon Blanc", "Kim Crawford"),
        ("Pinot Noir", "Kim Crawford"),
        ("Chardonnay", "Kim Crawford"),
        ("Chianti Classico", "Ruffino"),
        ("Brunello di Montalcino", "Banfi"),
        ("Chardonnay", "Sonoma-Cutrer"),
        ("Cabernet Sauvignon", "Jordan"),
        ("Chardonnay", "Jordan"),
        ("Malbec", "Luigi Bosca"),
        ("Torrontés", "Luigi Bosca"),
        ("Carménère", "Concha y Toro"),
        ("Cabernet Sauvignon", "Concha y Toro"),
        ("Sauvignon Blanc", "Concha y Toro"),
        ("Cava", "Freixenet"),
        ("Cava", "Codorníu"),
        ("Albariño", "Martin Códax"),
        ("Rioja", "Marqués de Cáceres"),
        ("Priorat", "Clos Mogador"),
        ("Chardonnay", "Rombauer"),
        ("Cabernet Sauvignon", "Caymus"),
        ("Cabernet Sauvignon", "Silver Oak"),
        ("Pinot Noir", "Laetitia"),
        ("Chardonnay", "Sonoma-Loeb"),
        ("Zinfandel", "Ridge"),
        ("Chardonnay", "Ramey"),
        ("Sancerre", "Domaines Schlumberger"),
        ("Chablis", "William Fèvre"),
        ("Chablis", "Domaine Laroche"),
        ("Pouilly-Fumé", "Domaines Saget"),
        ("Chardonnay", "Louis Jadot"),
        ("Pinot Noir", "Louis Jadot"),
        ("Beaujolais", "Louis Jadot"),
        ("Chablis", "Louis Jadot"),
        ("Châteauneuf-du-Pape", "Château de Beaucastel"),
        ("Côtes du Rhône", "M. Chapoutier"),
        ("Hermitage", "M. Chapoutier"),
        ("Chardonnay", "Château Ste. Michelle"),
        ("Riesling", "Château Ste. Michelle"),
        ("Merlot", "Château Ste. Michelle"),
        ("Prosecco", "Mionetto"),
        ("Amarone", "Masi"),
        ("Valpolicella", "Masi"),
        ("Pinot Grigio", "Livio Felluga"),
        ("Barolo", "Vietti"),
        ("Barbaresco", "Vietti"),
        ("Barbaresco", "Gaja"),
        ("Barolo", "Gaja"),
        ("Brunello", "Fattoria dei Barbi"),
        ("Verdicchio", "Fattoria Coroncino"),
        ("Montepulciano", "Cantina Tollo"),
        ("Chardonnay", "Trivento"),
        ("Malbec", "Trivento"),
        ("Torrontés", "Trivento"),
        ("Malbec", "Achaval-Ferrer"),
        ("Cabernet Sauvignon", "Catena"),
        ("Chardonnay", "Catena"),
        ("Shiraz", "d'Arenberg"),
        ("Grenache", "d'Arenberg"),
        ("Riesling", "Peter Lehmann"),
        ("Shiraz", "Peter Lehmann"),
        ("Semillon", "Peter Lehmann"),
        ("Shiraz", "Wolf Blass"),
        ("Chardonnay", "Wolf Blass"),
        ("Cabernet Sauvignon", "Wolf Blass"),
        ("Sauvignon Blanc", "Villa Maria"),
        ("Chardonnay", "Villa Maria"),
        ("Pinot Noir", "Villa Maria"),
        ("Chardonnay", "Cloudy Bay"),
        ("Sauvignon Blanc", "Cloudy Bay"),
        ("Champagne", "Moët & Chandon"),
        ("Champagne", "Veuve Clicquot"),
        ("Champagne", "Dom Pérignon"),
        ("Champagne", "Taittinger"),
        ("Champagne", "Laurent-Perrier"),
        ("Cava", "Segura Viudas"),
        ("Prosecco", "Zonin"),
    ]

    /// Terim name veya brand içinde geçen ürünleri döner. Ağ yok; anında.
    static func matching(_ term: String) -> [OFFProduct] {
        let t = term.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !t.isEmpty else { return [] }
        var out: [OFFProduct] = []
        for (idx, e) in entries.enumerated() {
            let name = e.name.lowercased()
            let brand = e.brand.lowercased()
            if name.contains(t) || brand.contains(t) {
                out.append(OFFProduct(
                    code: "vitis-local-\(idx)",
                    productName: e.name,
                    brands: e.brand,
                    imageUrl: nil
                ))
            }
        }
        return out
    }
}
