//
//  PrivacyPolicyView.swift
//  Pari
//
//  In-app Privacy Policy. GDPR & CCPA compliant. Last updated March 2025.
//

import SwiftUI

struct PrivacyPolicyView: View {
    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 28) {
                legalHeader(
                    title: "Privacy Policy",
                    effectiveDate: "Effective: March 1, 2025"
                )

                intro

                section("1. Information We Collect") {
                    subhead("1.1 Information You Provide")
                    body("• Phone number (used for authentication via one-time passcode)")
                    body("• Email address (optional; used for account recovery)")
                    body("• Full name, username, bio, profile photo (optional; for your public profile)")
                    body("• Instagram handle (optional; displayed on your profile)")
                    body("• Wine tastings: wine name, rating, tasting notes, comments, visibility setting, and moment photos you choose to capture")

                    subhead("1.2 Information Generated by Your Use")
                    body("• Activity data: tastings you log, wines you wishlist, users you follow, and cheers you give")
                    body("• Taste profile: regional preferences and grape preferences computed from your ratings")
                    body("• Contacts (optional): if you grant permission, we hash your contacts using a one-way function to help you find friends. We never store raw contact data.")
                    body("• Device information: device type, OS version, and app version (for crash diagnostics only)")
                    body("• Usage analytics: screens viewed, features used, error events (no advertising identifiers)")

                    subhead("1.3 Information From Third Parties")
                    body("• Wine metadata: product names, producer names, and label images are sourced from Open Food Facts (openfoodfacts.org), which is a publicly available open database.")
                }

                section("2. How We Use Your Information") {
                    body("We use your information to:")
                    body("• Provide and improve the Pari service")
                    body("• Power features: Taste Twin similarity, Taste Profile, Reserve List, social feed")
                    body("• Send transactional notifications (cheers, new followers). You can opt out in Settings.")
                    body("• Detect and prevent abuse, fraud, and policy violations")
                    body("• Comply with legal obligations")
                    body("We do not use your data for advertising or sell it to third-party advertisers.")
                }

                section("3. Legal Basis for Processing (EU/UK Users)") {
                    body("If you are in the European Economic Area (EEA), United Kingdom, or Switzerland, we process your personal data on the following legal bases:")
                    body("• Contract: to provide the service you signed up for")
                    body("• Legitimate interests: to improve the service, prevent abuse, and ensure security, balanced against your rights.")
                    body("• Consent: for optional features such as contact matching (you may withdraw consent at any time in Settings)")
                    body("• Legal obligation: where required by applicable law")
                }

                section("4. Sharing Your Information") {
                    body("We do not sell your personal data. We share data only in these limited circumstances:")
                    body("• Service providers: cloud hosting (Supabase/AWS), analytics, and crash reporting, bound by data processing agreements")
                    body("• Other users: your public profile, tastings with public visibility, and social activity (follows, cheers) are visible to other Pari users per your privacy settings")
                    body("• Legal requirements: when required by law, regulation, or valid legal process")
                    body("• Business transfers: in the event of a merger or acquisition, your data may be transferred subject to equivalent privacy protections")
                }

                section("5. Your Privacy Settings") {
                    body("You control who can see your cellar, wishlist, and activity in Settings → Privacy Settings. Options include: Everyone, Friends Only, or Only Me.")
                    body("Tastings you post with \"Only Me\" visibility are never shared with other users or displayed in the feed.")
                }

                section("6. Data Retention") {
                    body("We retain your account data for as long as your account is active. When you delete your account, we delete your personal data within 30 days, except where retention is required by law or for fraud prevention.")
                    body("Aggregated, de-identified statistical data (e.g., total tastings per wine) may be retained indefinitely as it cannot be linked back to you.")
                }

                section("7. Your Rights") {
                    body("Depending on your location, you may have the following rights:")
                    body("• Access: request a copy of the data we hold about you")
                    body("• Correction: update inaccurate data via Settings → Edit Profile")
                    body("• Deletion: delete your account and associated data in Settings → Delete Account")
                    body("• Portability: request your tasting data in a machine-readable format")
                    body("• Objection / Restriction: object to or restrict certain processing activities")
                    body("• Withdraw consent: revoke optional permissions (e.g., contact matching) at any time")
                    body("EU/UK users: you have the right to lodge a complaint with your local data protection authority. A list of EU supervisory authorities is available at edpb.europa.eu.")
                    body("California residents: Pari does not sell or share personal information for cross-context behavioral advertising. You may exercise your CCPA rights by contacting us at the address below.")
                    body("To exercise any right, contact us at privacy@pari.app or through Settings → Contact Concierge.")
                }

                section("8. International Data Transfers") {
                    body("Pari is operated from Turkey and uses cloud infrastructure that may process data in the United States and European Union. Transfers outside the EEA are protected by Standard Contractual Clauses (SCCs) approved by the European Commission.")
                }

                section("9. Children's Privacy") {
                    body("Pari is not directed at children under 13 (or the applicable minimum age in your jurisdiction). We do not knowingly collect data from children. If you believe a child has provided us data, contact us and we will delete it promptly.")
                }

                section("10. Security") {
                    body("We implement industry-standard safeguards: encrypted data at rest and in transit (TLS), hashed phone numbers for contact matching, and access controls limiting employee access to personal data. No system is perfectly secure. Please use a strong, unique password for your account.")
                }

                section("11. Third-Party Links") {
                    body("Pari may display links to external sites (e.g., Instagram profiles). This Policy does not apply to those sites. Review their privacy policies independently.")
                }

                section("12. Changes to This Policy") {
                    body("We will notify you of material changes via in-app notice or email at least 14 days before they take effect. Continued use after the effective date constitutes acceptance.")
                }

                section("13. Contact") {
                    body("Data Controller: Pari\nEmail: privacy@pari.app\nFor data subject requests: Settings → Contact Concierge")
                    body("EU Representative: if you are in the EEA and have questions about our GDPR compliance, contact us at privacy@pari.app.")
                }

                Divider()
                    .padding(.top, 8)

                Text("This Privacy Policy was last updated March 1, 2025.")
                    .font(PariTheme.uiFont(size: 12))
                    .foregroundStyle(PariTheme.textTertiary(for: colorScheme))
                    .padding(.bottom, 40)
            }
            .padding(.horizontal, 24)
            .padding(.top, 24)
        }
        .background(PariTheme.backgroundPrimary(for: colorScheme).ignoresSafeArea())
        .navigationTitle("Privacy Policy")
        .navigationBarTitleDisplayMode(.inline)
    }

    // MARK: - Helpers

    private var intro: some View {
        Text("Pari values your privacy. This Policy explains what data we collect, how we use it, and your rights. It applies to all users globally, with additional rights for users in the European Economic Area (EEA), United Kingdom, and California.")
            .font(PariTheme.uiFont(size: 15))
            .foregroundStyle(PariTheme.textSecondary(for: colorScheme))
            .fixedSize(horizontal: false, vertical: true)
            .lineSpacing(3)
    }

    private func legalHeader(title: String, effectiveDate: String) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(title)
                .font(.system(.title2, design: .serif, weight: .regular))
                .foregroundStyle(PariTheme.textPrimary(for: colorScheme))
            Text(effectiveDate)
                .font(PariTheme.uiFont(size: 13))
                .foregroundStyle(PariTheme.textTertiary(for: colorScheme))
        }
    }

    private func section(_ title: String, @ViewBuilder content: () -> some View) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title)
                .font(PariTheme.uiFont(size: 15, weight: .semibold))
                .foregroundStyle(PariTheme.textPrimary(for: colorScheme))
            content()
        }
    }

    private func subhead(_ text: String) -> some View {
        Text(text)
            .font(PariTheme.uiFont(size: 14, weight: .medium))
            .foregroundStyle(PariTheme.textPrimary(for: colorScheme))
            .padding(.top, 4)
    }

    private func body(_ text: String) -> some View {
        Text(text)
            .font(PariTheme.uiFont(size: 15))
            .foregroundStyle(PariTheme.textSecondary(for: colorScheme))
            .fixedSize(horizontal: false, vertical: true)
            .lineSpacing(3)
    }
}

#Preview {
    NavigationStack {
        PrivacyPolicyView()
    }
}
